### ISSUE TITLE
The demo results seemly have some artifacts

### ISSUE THREAD

**Issue by lingtengqiu** [zjp-shadow/CharacterGen#13] opened 2024-07-09 17:49 UTC
Thanks for your great job.

I saw your demo results that illustrate some artifacts like broken holes?
![image](https://github.com/zjp-shadow/CharacterGen/assets/37240099/e8143046-010c-41e3-8679-dad98118bf38)

Are results right?

Or
Can you give me some suggestions to solve this problem?

**Comment by zjp-shadow** [comment] 2024-07-09 17:51
This is caused by the laplacian smooth, you can set the iteration to 0. I think this is caused by the vertex which are not merged. I will correct this mistask in the future.

**Comment by lingtengqiu** [comment] 2024-07-10 02:47
Thanks :)

**Closed** 2024-07-10 07:44 UTC
